name: computational-econ
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python>=3.10

  # Core Scientific Computing
  - numpy>=2.0.0
  - scipy>=1.11.0
  - sympy>=1.12
  - pandas>=2.3.0
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - pillow>=12.0.0

  # Numerical Methods
  - numba>=0.62.0
  - dask>=2025.10.0
  - distributed>=2025.10.0

  # Machine Learning
  - scikit-learn>=1.4.0
  - tensorflow>=2.15.0
  - keras>=3.0.0
  - statsmodels>=0.14.0
  - xgboost>=2.0.0
  - lightgbm>=4.0.0
  - pytorch>=2.1.0

  # Econometrics
  - arch>=6.0.0
  - linearmodels>=5.3

  # Bayesian Statistics
  - pymc>=5.10.0
  - arviz>=0.17.0

  # Network Analysis
  - networkx>=3.2
  - python-igraph>=0.11.0

  # Data Acquisition
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - pandas-datareader>=0.10.0

  # Jupyter
  - jupyterlab>=4.0.0
  - jupyter>=1.0.0
  - ipython>=8.20.0
  - ipykernel>=6.28.0
  - ipywidgets>=8.1.0
  - nbformat>=5.10.0
  - notebook>=7.0.0

  # Testing
  - pytest>=8.0.0
  - pytest-cov>=4.1.0

  # Code Quality
  - black>=24.0.0
  - flake8>=7.0.0
  - mypy>=1.8.0

  # Utilities
  - cloudpickle>=3.1.0
  - graphviz>=0.21
  - python-dateutil>=2.9.0
  - pytz>=2025.2
  - pyyaml>=6.0.0
  - click>=8.3.0
  - toolz>=1.1.0
  - tqdm>=4.66.0
  - psutil>=7.0.0

  # Data Formats
  - pyarrow>=21.0.0
  - fastparquet>=2024.2.0
  - openpyxl>=3.1.0
  - xlrd>=2.0.0
  - pytables>=3.9.0

  # Pip-only packages
  - pip
  - pip:
    - quantecon>=0.7.0
    - yfinance>=0.2.0
    - fredapi>=0.5.0
    - memory_profiler>=0.61.0
    - cupy-cuda12x>=13.0.0  # Optional: requires NVIDIA GPU
