"""
Academic Diagram Style and Design System Tokens for Computational Economics and Data Science.

Provides unified styling, publication-ready color palettes (CVPR/NeurIPS/Econometrica standards),
safe metadata serialization, and drawing helpers.
"""

import json
import os

import matplotlib.patches as patches
import matplotlib.pyplot as plt

# --- Design Tokens ---
COLORS = {
    "primary": "#1E3A8A",  # Deep Navy
    "secondary": "#475569",  # Slate Gray
    "accent_green": "#059669",  # Emerald
    "accent_red": "#DC2626",  # Crimson
    "accent_amber": "#D97706",  # Amber / Orange
    "accent_purple": "#7C3AED",  # Purple
    "accent_cyan": "#0284C7",  # Cyan / Light Blue
    "bg_white": "#FFFFFF",  # Pure White
    "bg_card": "#F8FAFC",  # Card Background
    "border": "#CBD5E1",  # Light Border
    "text_dark": "#0F172A",  # Dark Slate
    "text_muted": "#64748B",  # Muted Gray
    "grid": "#E2E8F0",  # Grid Line
}

DPI = 300
FONT_FAMILY = "sans-serif"
METADATA_PATH = "images/metadata.json"


def apply_academic_style(ax=None, grid=True):
    """Applies clean academic styling to matplotlib axes."""
    plt.rcParams["font.sans-serif"] = [
        "DejaVu Sans",
        "Helvetica",
        "Arial",
        "sans-serif",
    ]
    plt.rcParams["axes.edgecolor"] = COLORS["border"]
    plt.rcParams["axes.linewidth"] = 0.8
    plt.rcParams["text.color"] = COLORS["text_dark"]
    plt.rcParams["axes.labelcolor"] = COLORS["text_dark"]
    plt.rcParams["xtick.color"] = COLORS["text_dark"]
    plt.rcParams["ytick.color"] = COLORS["text_dark"]

    if ax is not None:
        ax.set_facecolor(COLORS["bg_white"])
        if grid:
            ax.grid(
                True, linestyle="--", linewidth=0.5, color=COLORS["grid"], alpha=0.8
            )
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(COLORS["border"])
        ax.spines["bottom"].set_color(COLORS["border"])


def save_figure(fig, filepath, dpi=DPI):
    """Saves a figure with proper directory creation, tight bounds, and white background."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    fig.savefig(
        filepath,
        dpi=dpi,
        bbox_inches="tight",
        facecolor=COLORS["bg_white"],
        edgecolor="none",
    )
    plt.close(fig)
    print(f"  [SAVED] {filepath}")


def update_metadata(
    rel_filepath,
    description,
    source="Generated by course automation scripts",
    license_type="CC BY 4.0",
):
    """Updates the central images/metadata.json dictionary safely."""
    norm_path = rel_filepath.replace("\\", "/")
    if not os.path.exists(METADATA_PATH):
        data = {}
    else:
        try:
            with open(METADATA_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)
                if not isinstance(data, dict):
                    data = {}
        except Exception:
            data = {}

    data[norm_path] = {
        "description": description,
        "source": source,
        "license": license_type,
    }

    os.makedirs(os.path.dirname(METADATA_PATH), exist_ok=True)
    with open(METADATA_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def draw_card(
    ax,
    xy,
    width,
    height,
    title="",
    subtitle="",
    fill_color=COLORS["bg_card"],
    edge_color=COLORS["border"],
    box_style="round,pad=0.3,rounding_size=0.08",
):
    """Draws a sleek UI/academic card on matplotlib axes."""
    rect = patches.FancyBboxPatch(
        xy,
        width,
        height,
        boxstyle=box_style,
        facecolor=fill_color,
        edgecolor=edge_color,
        linewidth=1.2,
        zorder=2,
    )
    ax.add_patch(rect)
    cx = xy[0] + width / 2.0
    cy = xy[1] + height / 2.0
    if title and subtitle:
        ax.text(
            cx,
            cy + height * 0.15,
            title,
            ha="center",
            va="center",
            fontsize=11,
            fontweight="bold",
            color=COLORS["primary"],
            zorder=3,
        )
        ax.text(
            cx,
            cy - height * 0.18,
            subtitle,
            ha="center",
            va="center",
            fontsize=9,
            color=COLORS["text_muted"],
            zorder=3,
        )
    elif title:
        ax.text(
            cx,
            cy,
            title,
            ha="center",
            va="center",
            fontsize=10,
            fontweight="bold",
            color=COLORS["text_dark"],
            zorder=3,
        )
    return rect
