#!/usr/bin/env python3
"""Canonical image-asset provenance helpers.

The course keeps local image assets for authoring, but the public reading site
must not publish an asset whose origin/license is unknown.  This module makes
that distinction explicit instead of treating "file exists" as provenance.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IMAGES = ROOT / "images"
METADATA = IMAGES / "metadata.json"
IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"}
VAGUE_LICENSES = {"", "open source", "educational use", "unknown", "unverified"}

MARKDOWN_IMAGE_RE = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")
HTML_IMAGE_RE = re.compile(r"<img\b[^>]*\bsrc=[\"']([^\"']+)[\"'][^>]*>", re.IGNORECASE)


@dataclass(frozen=True)
class AssetProvenance:
    path: str
    status: str
    source: str
    license: str
    generator: str | None = None
    source_url: str | None = None
    creator: str | None = None
    attribution: str | None = None
    modifications: str | None = None
    retrieved_at: str | None = None

    @property
    def publishable(self) -> bool:
        return self.status in {"verified-generated", "verified-external"}


@lru_cache(maxsize=1)
def metadata() -> dict[str, dict]:
    if not METADATA.is_file():
        return {}
    payload = json.loads(METADATA.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("images/metadata.json must contain an object keyed by asset path")
    return payload


@lru_cache(maxsize=1)
def generator_sources() -> dict[str, str]:
    """Map assets explicitly named by course generation scripts to their script.

    Download scripts are deliberately excluded: downloading a file proves how
    it was acquired, not that the course owns or can relicense it.
    """
    scripts = [
        path
        for path in (ROOT / "scripts").glob("*.py")
        if not path.name.startswith("download_")
    ]
    texts = {path.name: path.read_text(encoding="utf-8", errors="ignore") for path in scripts}
    mapping: dict[str, str] = {}
    for asset in iter_assets():
        basename = Path(asset).name
        for name, text in texts.items():
            if asset in text or basename in text:
                mapping.setdefault(asset, f"scripts/{name}")
                break
    return mapping


def iter_assets() -> list[str]:
    if not IMAGES.is_dir():
        return []
    return sorted(
        path.relative_to(ROOT).as_posix()
        for path in IMAGES.rglob("*")
        if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES
    )


def provenance_for(asset: str | Path) -> AssetProvenance:
    path = Path(asset)
    if path.is_absolute():
        rel = path.resolve().relative_to(ROOT.resolve()).as_posix()
    else:
        rel = path.as_posix().lstrip("./")
    entry = metadata().get(rel, {})

    status = str(entry.get("provenance_status", "")).strip().lower()
    source = str(entry.get("source", "")).strip()
    license_name = str(entry.get("license", "")).strip()
    generator = entry.get("generator")

    if not status:
        # Existing course metadata historically identified generated assets with
        # this source string. Preserve that evidence while moving to the
        # explicit status schema.
        if "generated by course" in source.lower() and license_name:
            status = "verified-generated"
        elif rel in generator_sources():
            status = "verified-generated"
            generator = generator or generator_sources()[rel]
            source = source or "Generated by course source code"
            license_name = license_name or "CC BY 4.0"
        elif entry.get("source_url") and license_name.lower() not in VAGUE_LICENSES:
            status = "verified-external"
        else:
            status = "unverified"

    if status == "verified-generated" and not generator:
        generator = generator_sources().get(rel)

    return AssetProvenance(
        path=rel,
        status=status,
        source=source or ("Generated by course source code" if status == "verified-generated" else ""),
        license=license_name or ("CC BY 4.0" if status == "verified-generated" else "UNVERIFIED"),
        generator=generator,
        source_url=entry.get("source_url"),
        creator=entry.get("creator"),
        attribution=entry.get("attribution"),
        modifications=entry.get("modifications"),
        retrieved_at=entry.get("retrieved_at"),
    )


def is_publishable(asset: str | Path) -> bool:
    return provenance_for(asset).publishable


def _normalize_reference(source: Path, target: str) -> str | None:
    target = target.strip().split("#", 1)[0].split("?", 1)[0].strip("<>\"'")
    if not target or re.match(r"^(?:https?:|data:|attachment:)", target, re.I):
        return None
    resolved = (source.parent / target).resolve()
    try:
        return resolved.relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return None


def source_references() -> dict[str, set[str]]:
    """Return real local image references from canonical source documents."""
    references: dict[str, set[str]] = {}
    suffixes = {".ipynb", ".md", ".html", ".py", ".yml", ".yaml"}
    for source in ROOT.rglob("*"):
        if not source.is_file() or source.suffix.lower() not in suffixes:
            continue
        rel_source = source.relative_to(ROOT).as_posix()
        if rel_source.startswith(("docs/notebooks/", ".git/", "site/", "build/")):
            continue
        text = source.read_text(encoding="utf-8", errors="ignore")
        for match in MARKDOWN_IMAGE_RE.finditer(text):
            rel = _normalize_reference(source, match.group(1))
            if rel and (ROOT / rel).is_file():
                references.setdefault(rel, set()).add(rel_source)
        for match in HTML_IMAGE_RE.finditer(text):
            rel = _normalize_reference(source, match.group(1))
            if rel and (ROOT / rel).is_file():
                references.setdefault(rel, set()).add(rel_source)
    return references


def catalog_markdown() -> str:
    refs = source_references()
    lines = [
        "# Image Catalog and Provenance Ledger",
        "",
        "This catalog is generated from the actual `images/` tree, source references,",
        "and `images/metadata.json`. It is the publication ledger for course figures.",
        "",
        "Assets marked **unverified** remain available for local authoring but are not",
        "published by the generated reading site until their provenance is verified.",
        "",
        "| Asset | Status | Referenced by | Source / generator | License |",
        "|---|---|---:|---|---|",
    ]
    for asset in iter_assets():
        p = provenance_for(asset)
        source = p.generator or p.source or "—"
        lines.append(
            f"| `{asset}` | {p.status} | {len(refs.get(asset, set()))} | "
            f"{source.replace('|', '\\|')} | {p.license.replace('|', '\\|')} |"
        )
    lines += [
        "",
        "## Publication rule",
        "",
        "- `verified-generated`: generated by course source code or otherwise documented as an original course figure.",
        "- `verified-external`: source page/creator/license are recorded precisely in `images/metadata.json`.",
        "- `unverified`: origin or license is incomplete; the public reading-site generator omits the asset and leaves a provenance notice in its place.",
        "",
        "This rule prevents an incomplete rights ledger for one figure from blocking the",
        "rest of the local course while also preventing that figure from being silently",
        "published without reviewable provenance.",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(catalog_markdown(), end="")
