#!/usr/bin/env python3
"""Generate searchable MkDocs pages from every course notebook without executing it."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = ROOT / "docs" / "notebooks"
REPO = "https://github.com/AmirrezaFarnamTaheri/Computational-Economics-and-Data-Science"
RAW = "https://raw.githubusercontent.com/AmirrezaFarnamTaheri/Computational-Economics-and-Data-Science/main"
IMAGE_RE = re.compile(r"(!\[[^\]]*\]\()([^)]+)(\))")
LINK_RE = re.compile(r"(\[[^\]]+\]\()([^)]+\.ipynb(?:#[^)]*)?)(\))")

TRACKS = [
    "01-Foundations", "02-Numerical-Methods", "03-Economic-Modeling", "04-Macro-Models",
    "05-Micro-Models", "06-Econometrics", "07-Machine-Learning", "08-Time-Series",
    "09-Finance", "10-Specialized-Models", "Appendix", "high_performance_python",
]


def source(cell: dict) -> str:
    value = cell.get("source", "")
    return "".join(value) if isinstance(value, list) else str(value)


def rewrite_links(text: str, notebook: Path) -> str:
    def image(match: re.Match[str]) -> str:
        target = match.group(2).strip()
        if re.match(r"^(?:https?:|data:|attachment:)", target, re.I):
            return match.group(0)
        resolved = (notebook.parent / target.split("#", 1)[0]).resolve()
        try:
            rel = resolved.relative_to(ROOT.resolve()).as_posix()
        except ValueError:
            return match.group(0)
        return f"{match.group(1)}{RAW}/{rel}{match.group(3)}"

    def notebook_link(match: re.Match[str]) -> str:
        target = match.group(2)
        file_part, *anchor = target.split("#", 1)
        resolved = (notebook.parent / file_part).resolve()
        try:
            rel = resolved.relative_to(ROOT.resolve()).as_posix()
        except ValueError:
            return match.group(0)
        suffix = f"#{anchor[0]}" if anchor else ""
        return f"{match.group(1)}{REPO}/blob/main/{rel}{suffix}{match.group(3)}"

    return LINK_RE.sub(notebook_link, IMAGE_RE.sub(image, text))


def convert(notebook: Path) -> str:
    nb = json.loads(notebook.read_text(encoding="utf-8"))
    rel = notebook.relative_to(ROOT).as_posix()
    lines = [
        "<!-- AUTO-GENERATED by scripts/notebooks_to_docs.py; edit the notebook source instead. -->",
        "",
        f'> **Source notebook:** [`{rel}`]({REPO}/blob/main/{rel})',
        "",
        "> Notebook outputs are intentionally omitted from the documentation build; code and narrative remain source-faithful.",
        "",
    ]
    for cell in nb.get("cells", []):
        text = source(cell).rstrip()
        if not text:
            continue
        if cell.get("cell_type") == "markdown":
            lines += [rewrite_links(text, notebook), ""]
        elif cell.get("cell_type") == "code":
            lines += ["```python", text, "```", ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--clean", action="store_true")
    args = parser.parse_args()
    if args.clean and DOCS_ROOT.exists():
        import shutil
        shutil.rmtree(DOCS_ROOT)
    written = 0
    for track in TRACKS:
        for notebook in sorted((ROOT / track).glob("*.ipynb")):
            target = DOCS_ROOT / track / f"{notebook.stem}.md"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(convert(notebook), encoding="utf-8")
            written += 1
    print(f"Generated {written} notebook documentation pages in {DOCS_ROOT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
