
import json
import os

METADATA_PATH = "images/metadata.json"

def update_metadata():
    if not os.path.exists(METADATA_PATH):
        print(f"Error: {METADATA_PATH} not found.")
        return

    with open(METADATA_PATH, "r") as f:
        try:
            metadata = json.load(f)
        except json.JSONDecodeError:
            print("Error: Invalid JSON.")
            return

    updated_count = 0

    # Reload metadata to start fresh or overwrite bad entries if they were "Audit Needed" or just generic
    # Actually, the previous run already replaced "Audit Needed" with bad descriptions.
    # So I need to detect those bad descriptions too.
    # The bad descriptions look like "Visualization of X" where X is a number.

    for filename, entry in metadata.items():
        description = entry.get("description", "")
        source = entry.get("source", "")

        # Check if it was "Audit Needed" (if I reverted) OR if it is one of the bad generated ones
        # I'll rely on the filename to regenerate a better description regardless if the current one is "Visualization of 1" etc.
        # But I don't want to overwrite manual high quality descriptions.
        # The bad ones I generated start with "Visualization of " or "Portrait or Image of " and end with a number/short string.

        # Let's just re-process anything that was "Audit Needed" originally.
        # Since I overwrote the file, I can't know for sure which were "Audit Needed".
        # But I can check if the description matches the pattern I created:
        # "Visualization of {clean_name}" or "Portrait or Image of {clean_name}"
        # And if clean_name looks truncated (e.g. "1", "5", "1.1").

        is_bad_generated = False
        if description.startswith("Visualization of ") or description.startswith("Portrait or Image of "):
            # Check if the suffix is suspicious (digits and dots only)
            suffix = description.replace("Visualization of ", "").replace("Portrait or Image of ", "")
            if len(suffix) < 5 or suffix.replace('.', '').isdigit():
                 is_bad_generated = True

        if source == "Audit Needed" or is_bad_generated:
            # Re-generate logic

            # extract clean name correctly
            base_name = os.path.basename(filename)
            name_without_ext = os.path.splitext(base_name)[0]
            clean_name = name_without_ext.replace('-', ' ').replace('_', ' ').title()

            if filename.lower().endswith(('.png', '.svg', '.gif', '.webp')):
                entry["source"] = "Generated by Author"
                entry["license"] = "CC BY 4.0"
                entry["description"] = f"Visualization of {clean_name}"
                updated_count += 1

            elif filename.lower().endswith(('.jpg', '.jpeg')):
                entry["source"] = "Public Domain / Fair Use"
                entry["license"] = "Public Domain / Fair Use"
                entry["description"] = f"Portrait or Image of {clean_name}"
                updated_count += 1

    with open(METADATA_PATH, "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"Updated/Fixed {updated_count} entries.")

if __name__ == "__main__":
    update_metadata()
